### ISSUE TITLE
Fails with vega-view: Symbol’s function definition is void: assert

### ISSUE THREAD

**Issue by stathissideris** [applied-science/emacs-vega-view#1]
Calling vega-view fails with 
```
vega-view: Symbol’s function definition is void: assert
```
 in GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31

**Comment by jackrusher** [comment]
I just added a `(require 'cl-lib)`, which should should make this problem go away. Would you pull the latest and let me know if it works for you?

**Comment by jackrusher** [comment]
@stathissideris help me out here! :)

**Comment by stathissideris** [comment]
Sorry, still getting the same error!

**Comment by stathissideris** [comment]
I removed the asserts and re-eval'ed the relevant functions and it complained about `case` being void. My cl-lib is on version 1.0.

**Comment by jackrusher** [comment]
Hm. That's quite interesting, as both `assert` and `case` are provided by `cl-lib`. Would you try changing those calls to use their prefixes? That is, `cl-assert` and `cl-case` to see if it resolves the issue?

**Comment by stathissideris** [comment]
Changing those calls to the prefixed versions seems to do the trick! I had to install json-mode to test it (I usually use javascript-mode for JSON). Also, it looks like my emacs can't display SVG (`Cannot display image: (Invalid image type ‘svg’)`) -- I probably don't have SVG support compiled in. I tried changing `vega-view--vega-command` to `"vl2png -b "` but I get this vega error:

```
TypeError: Cannot read property 'getContext' of null
    at resize (/usr/local/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3665:28)
    at CanvasRenderer.prototype$6.resize (/usr/local/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3714:5)
    at CanvasRenderer.prototype$4.initialize (/usr/local/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3294:17)
    at CanvasRenderer.prototype$6.initialize (/usr/local/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3709:28)
    at initializeRenderer (/usr/local/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:657:8)
    at renderHeadless (/usr/local/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:780:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async View.renderToCanvas [as toCanvas] (/usr/local/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:815:15)
```

**Comment by jackrusher** [comment]
@stathissideris Ok, I've added the `cl-` prefix to those macros in the code, plus added a check to make sure one of SVG/PNG is supported with automatic fail back to PNG if SVG isn't available. Would you pull the latest and let me know if it resolves your troubles?

Thanks for your help testing!

**Comment by stathissideris** [comment]
Yes I can confirm that the latest runs without any trouble. The PNG generation still fails with the error I pasted in my previous comment but I found through https://github.com/vega/vega/issues/666 that in order to generate PNGs you need to install node-canvas (`npm install -g canvas`) --  maybe add this to the readme? I tried installing canvas but it fails on my machine, so I either need to get to install somehow or get an emacs that can show SVGs. So it looks like it should work, but I haven't actually seen the plot yet!

**Comment by jackrusher** [comment]
Note added to README. I'm sorry things still don't work for you. :( In any case, now that the subject of this ticket is fixed, I'm going to close it.

**Comment by stathissideris** [comment]
Thank you for fixing it! I'll see if I can set up in order to be able to run vega-view, I think it's going to be very useful.

**Comment by genmeblog** [comment]
Let me leave a comment here about my road with nodejs.

I'm using WSL1 with Ubuntu 18.04 and I faced several problems which I list below.

1. Ubuntu 18.04 installs nodejs v8 which requires old libssl (1.0). When you have newer libssl on your system installation of nodejs-dev and npm fails. See this [discussion](https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1794589).
2. On nodejs v8 and WSL you can't run `vl2svg` required by this library. I was getting this error: `{ Error: ESPIPE: invalid seek, read errno: -29, code: 'ESPIPE', syscall: 'read' }`. 
3. Installing npm modules globally (-g) can cause `EACCES` error and some stuff is installed partially (eg. vega is installed but canvas not).
4. I was getting `TypeError: Cannot read property 'getContext' of null` error too. I found that can mean everything, like wrong configuration in `.npmrc`.

Solution:
1. Wipe out everything you've done to the date. Yes, the mess I found on my PC was really huge.
    - uninstall nodejs and npm/npx
    - in my case also uninstall Windows versions
    - remove `node_modules` from `/home/user`,  `/root`,  `/usr/local/lib/`
    - remove `.npm` folders, both from `/root` and `/home/user`.
    - remove any `.npm...` or `.node...` files from home directories (eg. `.npmrc`).
    - remove any dead links from `/usr/local/bin`
    - check $PATH to be sure that nothing is left
1. Bump `nodejs` version to minimum 10. Install from source or from PPA.
2. Install modules globally but using local folder! Follow [this official](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) instructions.
3. What helped me also, I installed `canvas` from source. [Instructions](https://www.npmjs.com/package/canvas).
