### ISSUE TITLE
"vega-view was unable to parse the preceding sexp!"

### ISSUE THREAD

**Issue by willenbug** [applied-science/emacs-vega-view#13]
I'm trying to run this package for the first time. I have a file with the contents below (from the sample on the README). I place my cursor after the final `}`, then M-x and "vega-view". However, I get the error "vega-view was unable to parse the preceding sexp!".

```json
{
    "data": {
        "values": [
            {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
            {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
            {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
        ]
    },
    "mark": "bar",
    "encoding": {
        "x": {"field": "a", "type": "ordinal", "axis": {"labelAngle": 0}},
        "y": {"field": "b", "type": "quantitative"}
    }
}
```

I'm running GNU Emacs 27.2 and have vega-view 20210401.1115 installed.

I also installed the npm dependencies:
```
├── vega-cli@5.21.0
├── vega-lite@5.2.0
└── vega@5.21.0
```

Thank you!

**Comment by jackrusher** [comment]
Hi @willenbug! What mode was the buffer in when you issued that command? If you want it to know how to parse JSON, it must be in a mode that understands JSON syntax.

**Comment by willenbug** [comment]
Thanks for your time, @jackrusher. It's in JSON Mode.

**Comment by jackrusher** [comment]
Hm. I've just tried it here by copying from your example above and everything worked as expected. Could you try it again, but make sure the cursor is on the same line as, and immediately after, the `}`? It appears that `json-mode` won't parse the preceding sexp if there's whitespace between the closing `}` and the cursor.

**Comment by willenbug** [comment]
That was it! I was placing my cursor after a new-line. Inserting a space after the final `}` and placing my cursor there did the trick.

Thanks, again!

**Comment by jackrusher** [comment]
Glad it works for you! :)
