### ISSUE TITLE
emacs fails to convert svg to the image

### ISSUE THREAD

**Issue by genmeblog** [applied-science/emacs-vega-view#4]
My Emacs `GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2019-09-16` seems to be configured to delegate image conversion to ImageMagick (major mode is displayed as `Image[imagemagick]`. SVG is supported:

```lisp
(image-type-available-p 'svg)
t

(image-type-available-p 'imagemagick)
t
```

In Emacs following error is printed. Looks like ImageMagick is not able to infer format:

```
ImageMagick error: no decode delegate for this image format `' @ error/blob.c/BlobToImage/353
```

Additionally, Imagemagick has some issues with converting svg created by Vega.
When I call from shell this error is thrown:
```
convert-im6.q16: non-conforming drawing primitive definition `path' @ error/draw.c/RenderMVGContent/4300.
```

**Comment by genmeblog** [comment]
Just to give more info (as discussed on Zulip).

My Emacs is taken from [PPA](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs). And is compiled against `librsvg` and `imagemagick`

```
Dependencies: 
26.3~1.git96dd019-kk1+18.04 - emacs26-common (0 (null)) libasound2 (2 1.0.16) libc6 (2 2.25) 
libcairo2 (2 1.10.0) libdbus-1-3 (2 1.9.14) libfontconfig1 (2 2.12) libfreetype6 (2 2.2.1) libgdk-
pixbuf2.0-0 (2 2.22.0) libgif7 (2 5.1) libglib2.0-0 (2 2.37.3) libgnutls30 (2 3.5.6) libgpm2 (2 1.20.7) 
libgtk-3-0 (2 3.21.4) libice6 (2 1:1.0.0) libjavascriptcoregtk-4.0-18 (0 (null)) libjpeg8 (2 8c) liblcms2-2 
(2 2.2+git20110628) libm17n-0 (2 1.6.1) libmagickcore-6.q16-3 (2 8:6.9.6.8) libmagickwand-6.q16-3 
(2 8:6.9.6.8) libotf0 (2 0.9.11) libpango-1.0-0 (2 1.18.0) libpng16-16 (2 1.6.2-1) librsvg2-2 (2 2.14.4) 
libselinux1 (2 1.32) libsm6 (0 (null)) libsystemd0 (0 (null)) libtiff5 (2 4.0.3) libtinfo5 (2 6) 
libwebkit2gtk-4.0-37 (2 2.15.1) libx11-6 (0 (null)) libx11-xcb1 (0 (null)) libxcb1 (0 (null)) libxext6 (0 
(null)) libxfixes3 (2 1:4.0.1) libxft2 (4 2.1.1) libxml2 (2 2.7.4) libxpm4 (0 (null)) libxrender1 (0 (null)) 
zlib1g (2 1:1.1.4) emacs26-nox (0 (null)) emacs26-nox (0 (null)) 
```

System: Ubuntu 18.04.4 under WSL 1

**Comment by jackrusher** [comment]
@genmeblog I can't remember. Did we resolve this one?

**Comment by genmeblog** [comment]
Not really. We've switched to PNG rendering. Emacs compiled with ImageMagick still fails on certain types of charts (SVGs). Turning off IM conversion for SVG didn't work. Maybe mark it as "wontfix" as it's not related to the script and let's leave it for a while.
